
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD DIVIDE EQUALS EXPO GETSTACK GREET LPAREN MULTIPLY NAME NUMBER RPAREN STACKASCII STRING SUBTRACT\n    expression : NUMBER ADD NUMBER\n               | NUMBER SUBTRACT NUMBER\n               | NUMBER MULTIPLY NUMBER\n               | NUMBER DIVIDE NUMBER\n               | NUMBER EXPO NUMBER\n               | NAME ADD NUMBER\n               | NAME SUBTRACT NUMBER\n               | NAME MULTIPLY NUMBER\n               | NAME DIVIDE NUMBER\n               | NAME EXPO NUMBER\n               | NUMBER ADD NAME\n               | NUMBER SUBTRACT NAME\n               | NUMBER MULTIPLY NAME\n               | NUMBER DIVIDE NAME\n               | NUMBER EXPO NAME\n               | NAME ADD NAME\n               | NAME SUBTRACT NAME\n               | NAME MULTIPLY NAME\n               | NAME DIVIDE NAME\n               | NAME EXPO NAME\n    expression : GREET LPAREN NAME RPAREN\n    expression : NAME LPAREN NUMBER RPAREN\n               | NAME LPAREN STRING LPAREN RPAREN RPAREN\n    expression : STACKASCII LPAREN RPAREN\n    expression : GETSTACK LPAREN NUMBER RPAREN\n               | GETSTACK LPAREN STRING RPAREN\n    \n    expression : NAME EQUALS NUMBER\n               | NAME EQUALS STRING\n    \n    expression : NAME\n    '
    
_lr_action_items = {'NUMBER':([0,7,8,9,10,11,12,13,14,15,16,17,18,21,],[2,22,24,26,28,30,33,35,37,39,41,42,44,48,]),'NAME':([0,7,8,9,10,11,12,13,14,15,16,19,],[3,23,25,27,29,31,32,34,36,38,40,46,]),'GREET':([0,],[4,]),'STACKASCII':([0,],[5,]),'GETSTACK':([0,],[6,]),'$end':([1,3,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,44,45,47,50,52,53,54,56,],[0,-29,-1,-11,-2,-12,-3,-13,-4,-14,-5,-15,-16,-6,-17,-7,-18,-8,-19,-9,-20,-10,-27,-28,-24,-22,-21,-25,-26,-23,]),'ADD':([2,3,],[7,12,]),'SUBTRACT':([2,3,],[8,13,]),'MULTIPLY':([2,3,],[9,14,]),'DIVIDE':([2,3,],[10,15,]),'EXPO':([2,3,],[11,16,]),'LPAREN':([3,4,5,6,43,],[17,19,20,21,51,]),'EQUALS':([3,],[18,]),'STRING':([17,18,21,],[43,45,49,]),'RPAREN':([20,42,46,48,49,51,55,],[47,50,52,53,54,55,56,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> NUMBER ADD NUMBER','expression',3,'p_expression_operators','main.py',64),
  ('expression -> NUMBER SUBTRACT NUMBER','expression',3,'p_expression_operators','main.py',65),
  ('expression -> NUMBER MULTIPLY NUMBER','expression',3,'p_expression_operators','main.py',66),
  ('expression -> NUMBER DIVIDE NUMBER','expression',3,'p_expression_operators','main.py',67),
  ('expression -> NUMBER EXPO NUMBER','expression',3,'p_expression_operators','main.py',68),
  ('expression -> NAME ADD NUMBER','expression',3,'p_expression_operators','main.py',69),
  ('expression -> NAME SUBTRACT NUMBER','expression',3,'p_expression_operators','main.py',70),
  ('expression -> NAME MULTIPLY NUMBER','expression',3,'p_expression_operators','main.py',71),
  ('expression -> NAME DIVIDE NUMBER','expression',3,'p_expression_operators','main.py',72),
  ('expression -> NAME EXPO NUMBER','expression',3,'p_expression_operators','main.py',73),
  ('expression -> NUMBER ADD NAME','expression',3,'p_expression_operators','main.py',74),
  ('expression -> NUMBER SUBTRACT NAME','expression',3,'p_expression_operators','main.py',75),
  ('expression -> NUMBER MULTIPLY NAME','expression',3,'p_expression_operators','main.py',76),
  ('expression -> NUMBER DIVIDE NAME','expression',3,'p_expression_operators','main.py',77),
  ('expression -> NUMBER EXPO NAME','expression',3,'p_expression_operators','main.py',78),
  ('expression -> NAME ADD NAME','expression',3,'p_expression_operators','main.py',79),
  ('expression -> NAME SUBTRACT NAME','expression',3,'p_expression_operators','main.py',80),
  ('expression -> NAME MULTIPLY NAME','expression',3,'p_expression_operators','main.py',81),
  ('expression -> NAME DIVIDE NAME','expression',3,'p_expression_operators','main.py',82),
  ('expression -> NAME EXPO NAME','expression',3,'p_expression_operators','main.py',83),
  ('expression -> GREET LPAREN NAME RPAREN','expression',4,'p_greet','main.py',97),
  ('expression -> NAME LPAREN NUMBER RPAREN','expression',4,'p_pushstack','main.py',104),
  ('expression -> NAME LPAREN STRING LPAREN RPAREN RPAREN','expression',6,'p_pushstack','main.py',105),
  ('expression -> STACKASCII LPAREN RPAREN','expression',3,'p_asciistack','main.py',113),
  ('expression -> GETSTACK LPAREN NUMBER RPAREN','expression',4,'p_getstack','main.py',121),
  ('expression -> GETSTACK LPAREN STRING RPAREN','expression',4,'p_getstack','main.py',122),
  ('expression -> NAME EQUALS NUMBER','expression',3,'p_declarevariable','main.py',131),
  ('expression -> NAME EQUALS STRING','expression',3,'p_declarevariable','main.py',132),
  ('expression -> NAME','expression',1,'p_usevariable','main.py',141),
]
